/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Deterministic Lua, XML, and SQL AST-Safe Code Generation Engine
 * for FiveM Server Frameworks (QBCore, ESX Legacy, Standalone, and GTA V handling.meta)
 */

export type SupportedFramework = 'qbcore' | 'esx_legacy' | 'standalone_lua' | 'handling_meta';
export type ConfigCategory = 'economy_jobs' | 'item_registry' | 'vehicle_shop' | 'handling_tuner' | 'full_bundle';

export interface JobGrade {
  grade: number;
  name: string;
  label: string;
  payment: number;
  isBoss?: boolean;
}

export interface JobConfig {
  id: string;
  name: string;
  label: string;
  defaultDuty: boolean;
  offDutyPay: boolean;
  riskFactor: number; // 1.0 (Safe / Legal) to 3.0 (Extreme Illegal)
  cycleMinutes: number; // Average time to complete 1 job cycle
  isIllegal?: boolean;
  grades: JobGrade[];
}

export interface ItemConfig {
  name: string;
  label: string;
  weight: number; // In grams
  type: 'item' | 'weapon' | 'consumable';
  image: string;
  unique: boolean;
  useable: boolean;
  shouldClose: boolean;
  description: string;
  buyPrice?: number;
  sellPrice?: number;
  decayRate?: number; // Daily percentage (0 - 100)
}

export interface ServerConfigProject {
  configId: string;
  ownerDiscordId: string;
  projectName: string;
  framework: SupportedFramework;
  category: ConfigCategory;
  economyBaselines: {
    targetSupercarPrice: number;
    targetAverageHourlyWage: number;
    taxRatePercentage: number;
    paycheckIntervalMinutes: number;
    startingBankBalance: number;
    startingCashBalance: number;
  };
  jobs: JobConfig[];
  items: ItemConfig[];
  customHandling?: Record<string, number>;
  generatedCode: string;
  createdAt: number;
  updatedAt: number;
  isProExport: boolean;
}

export interface EconomyMetrics {
  avgHourlyWage: number;
  legalAvgHourlyWage: number;
  illegalAvgHourlyWage: number;
  wageDisparityRatio: number; // Illegal vs Legal ratio
  hoursToStarterCar: number; // ~$25,000
  hoursToMidSedan: number; // ~$85,000
  hoursToSupercar: number; // Baseline target
  hoursToLuxuryVilla: number; // ~$3,500,000
  giniIndex: number; // 0.0 - 1.0
  velocityScore: number; // 0 - 100
  rating: 'Optimal' | 'Slightly Inflated' | 'Hyper-Inflated' | 'Grindy' | 'Extreme Disparity';
  ratingColor: string;
  recommendations: string[];
}

/**
 * Escapes strings for Lua literal single/double quotes safely.
 */
export function escapeLuaString(str: string): string {
  if (!str) return '';
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"');
}

/**
 * Generates deterministic QBCore Job Configuration (QBShared.Jobs)
 */
export function generateQBCoreJobs(jobs: JobConfig[]): string {
  const lines: string[] = [];
  lines.push('-- ====================================================================');
  lines.push('-- Generated by ViceIntel FiveM Script Studio (Deterministic Lua Engine)');
  lines.push('-- Framework: QBCore Framework (QBShared.Jobs)');
  lines.push('-- Target: resources/[qb]/qb-core/shared/jobs.lua');
  lines.push('-- ====================================================================');
  lines.push('');
  lines.push('QBShared = QBShared or {}');
  lines.push('QBShared.Jobs = QBShared.Jobs or {}');
  lines.push('');

  jobs.forEach((job) => {
    const jobKey = job.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`QBShared.Jobs['${jobKey}'] = {`);
    lines.push(`    label = '${escapeLuaString(job.label)}',`);
    lines.push(`    defaultDuty = ${job.defaultDuty ? 'true' : 'false'},`);
    lines.push(`    offDutyPay = ${job.offDutyPay ? 'true' : 'false'},`);
    lines.push(`    grades = {`);

    const sortedGrades = [...job.grades].sort((a, b) => a.grade - b.grade);
    sortedGrades.forEach((g) => {
      lines.push(`        ['${g.grade}'] = {`);
      lines.push(`            name = '${escapeLuaString(g.name)}',`);
      lines.push(`            payment = ${Math.round(g.payment)},`);
      if (g.isBoss) {
        lines.push(`            isboss = true,`);
      }
      lines.push(`        },`);
    });

    lines.push(`    },`);
    lines.push(`}`);
    lines.push('');
  });

  return lines.join('\n');
}

/**
 * Generates deterministic ESX Legacy Job Configuration and SQL Migrations
 */
export function generateESXJobs(jobs: JobConfig[]): string {
  const lines: string[] = [];
  lines.push('-- ====================================================================');
  lines.push('-- Generated by ViceIntel FiveM Script Studio (Deterministic Lua Engine)');
  lines.push('-- Framework: ESX Legacy (Config.Jobs & Database Schema)');
  lines.push('-- Target: resources/[esx]/es_extended/config.jobs.lua');
  lines.push('-- ====================================================================');
  lines.push('');
  lines.push('Config = Config or {}');
  lines.push('Config.Jobs = Config.Jobs or {}');
  lines.push('');

  jobs.forEach((job) => {
    const jobKey = job.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`Config.Jobs['${jobKey}'] = {`);
    lines.push(`    label = '${escapeLuaString(job.label)}',`);
    lines.push(`    whitelisted = ${job.riskFactor < 1.5 ? 'false' : 'true'},`);
    lines.push(`    grades = {`);

    const sortedGrades = [...job.grades].sort((a, b) => a.grade - b.grade);
    sortedGrades.forEach((g) => {
      lines.push(`        ['${g.grade}'] = {`);
      lines.push(`            name = '${escapeLuaString(g.name)}',`);
      lines.push(`            label = '${escapeLuaString(g.label || g.name)}',`);
      lines.push(`            salary = ${Math.round(g.payment)},`);
      lines.push(`            skin_male = {},`);
      lines.push(`            skin_female = {},`);
      lines.push(`        },`);
    });

    lines.push(`    }`);
    lines.push(`}`);
    lines.push('');
  });

  lines.push('-- --------------------------------------------------------------------');
  lines.push('-- ESX Database SQL Migrations (Execute in HeidiSQL / phpMyAdmin):');
  lines.push('-- --------------------------------------------------------------------');
  lines.push('/*');
  jobs.forEach((job) => {
    const jobKey = job.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`INSERT IGNORE INTO \`jobs\` (\`name\`, \`label\`, \`whitelisted\`) VALUES ('${jobKey}', '${escapeLuaString(job.label)}', ${job.riskFactor >= 1.5 ? 1 : 0});`);
    job.grades.forEach((g) => {
      lines.push(`INSERT IGNORE INTO \`job_grades\` (\`job_name\`, \`grade\`, \`name\`, \`label\`, \`salary\`, \`skin_male\`, \`skin_female\`) VALUES ('${jobKey}', ${g.grade}, '${escapeLuaString(g.name)}', '${escapeLuaString(g.label || g.name)}', ${Math.round(g.payment)}, '{}', '{}');`);
    });
  });
  lines.push('*/');

  return lines.join('\n');
}

/**
 * Generates deterministic QBCore Items Table (QBShared.Items)
 */
export function generateQBCoreItems(items: ItemConfig[]): string {
  const lines: string[] = [];
  lines.push('-- ====================================================================');
  lines.push('-- Generated by ViceIntel FiveM Script Studio (Deterministic Lua Engine)');
  lines.push('-- Framework: QBCore Framework (QBShared.Items)');
  lines.push('-- Target: resources/[qb]/qb-core/shared/items.lua');
  lines.push('-- ====================================================================');
  lines.push('');
  lines.push('QBShared = QBShared or {}');
  lines.push('QBShared.Items = QBShared.Items or {}');
  lines.push('');

  items.forEach((item) => {
    const itemKey = item.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`QBShared.Items['${itemKey}'] = {`);
    lines.push(`    name = '${itemKey}',`);
    lines.push(`    label = '${escapeLuaString(item.label)}',`);
    lines.push(`    weight = ${Math.max(0, Math.round(item.weight))},`);
    lines.push(`    type = '${item.type || 'item'}',`);
    lines.push(`    image = '${escapeLuaString(item.image || `${itemKey}.png`)}',`);
    lines.push(`    unique = ${item.unique ? 'true' : 'false'},`);
    lines.push(`    useable = ${item.useable ? 'true' : 'false'},`);
    lines.push(`    shouldClose = ${item.shouldClose ? 'true' : 'false'},`);
    lines.push(`    combinable = nil,`);
    lines.push(`    description = '${escapeLuaString(item.description || item.label)}',`);
    if (item.decayRate && item.decayRate > 0) {
      lines.push(`    decay = ${item.decayRate},`);
    }
    lines.push(`}`);
    lines.push('');
  });

  return lines.join('\n');
}

/**
 * Generates deterministic ESX / ox_inventory Items Configuration
 */
export function generateESXItems(items: ItemConfig[]): string {
  const lines: string[] = [];
  lines.push('-- ====================================================================');
  lines.push('-- Generated by ViceIntel FiveM Script Studio (Deterministic Lua Engine)');
  lines.push('-- Framework: ox_inventory / ESX Items Definition');
  lines.push('-- Target: resources/[inventory]/ox_inventory/data/items.lua');
  lines.push('-- ====================================================================');
  lines.push('');
  lines.push('return {');

  items.forEach((item) => {
    const itemKey = item.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`    ['${itemKey}'] = {`);
    lines.push(`        label = '${escapeLuaString(item.label)}',`);
    lines.push(`        weight = ${Math.max(0, Math.round(item.weight))},`);
    lines.push(`        stack = ${item.unique ? 'false' : 'true'},`);
    lines.push(`        close = ${item.shouldClose ? 'true' : 'false'},`);
    lines.push(`        description = '${escapeLuaString(item.description || item.label)}',`);
    if (item.type === 'consumable') {
      lines.push(`        consume = 1,`);
      lines.push(`        client = {`);
      lines.push(`            status = { hunger = 200000, thirst = 200000 },`);
      lines.push(`            anim = { dict = 'mp_player_inteat@burger', clip = 'mp_player_int_eat_burger' },`);
      lines.push(`        },`);
    }
    lines.push(`    },`);
  });

  lines.push('}');
  lines.push('');
  lines.push('-- --------------------------------------------------------------------');
  lines.push('-- Legacy ESX Database Schema SQL Migrations:');
  lines.push('-- --------------------------------------------------------------------');
  lines.push('/*');
  items.forEach((item) => {
    const itemKey = item.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
    lines.push(`INSERT IGNORE INTO \`items\` (\`name\`, \`label\`, \`weight\`, \`rare\`, \`can_remove\`) VALUES ('${itemKey}', '${escapeLuaString(item.label)}', ${Math.max(1, Math.round(item.weight / 100))}, 0, 1);`);
  });
  lines.push('*/');

  return lines.join('\n');
}

/**
 * Generates GTA V handling.meta XML with CHandlingDataMgr structure
 */
export function generateHandlingXML(params: Record<string, number>, handlingName = 'VICE_CUSTOM_SPEC'): string {
  const p = {
    fMass: params.fMass || 1550.0,
    fInitialDragCoeff: params.fInitialDragCoeff || 8.2,
    fDownforceModifier: params.fDownforceModifier || 1.85,
    fDriveBiasFront: params.fDriveBiasFront !== undefined ? params.fDriveBiasFront : 0.0,
    nInitialDriveGears: params.nInitialDriveGears || 6,
    fInitialDriveForce: params.fInitialDriveForce || 0.385,
    fDriveInertia: params.fDriveInertia || 1.0,
    fClutchChangeRateScaleUpShift: params.fClutchChangeRateScaleUpShift || 2.5,
    fClutchChangeRateScaleDownShift: params.fClutchChangeRateScaleDownShift || 2.5,
    fInitialDriveMaxFlatVel: params.fInitialDriveMaxFlatVel || 185.0,
    fBrakeForce: params.fBrakeForce || 1.15,
    fBrakeBiasFront: params.fBrakeBiasFront || 0.62,
    fHandBrakeForce: params.fHandBrakeForce || 0.85,
    fSteeringLock: params.fSteeringLock || 38.5,
    fTractionCurveMax: params.fTractionCurveMax || 2.45,
    fTractionCurveMin: params.fTractionCurveMin || 2.15,
    fTractionCurveLateral: params.fTractionCurveLateral || 22.5,
    fTractionSpringDeltaMax: params.fTractionSpringDeltaMax || 0.15,
    fLowSpeedTractionLossMult: params.fLowSpeedTractionLossMult || 1.0,
    fCamberStiffnesss: params.fCamberStiffnesss || 0.0,
    fTractionBiasFront: params.fTractionBiasFront || 0.48,
    fTractionLossMult: params.fTractionLossMult || 1.0,
    fSuspensionForce: params.fSuspensionForce || 2.65,
    fSuspensionCompDamp: params.fSuspensionCompDamp || 1.4,
    fSuspensionReboundDamp: params.fSuspensionReboundDamp || 2.1,
    fSuspensionUpperLimit: params.fSuspensionUpperLimit || 0.1,
    fSuspensionLowerLimit: params.fSuspensionLowerLimit || -0.12,
    fSuspensionRaise: params.fSuspensionRaise || 0.0,
    fSuspensionBiasFront: params.fSuspensionBiasFront || 0.5,
    fAntiRollBarForce: params.fAntiRollBarForce || 0.8,
    fAntiRollBarBiasFront: params.fAntiRollBarBiasFront || 0.5,
    fRollCentreHeightFront: params.fRollCentreHeightFront || 0.35,
    fRollCentreHeightRear: params.fRollCentreHeightRear || 0.35,
    fCollisionDamageMult: params.fCollisionDamageMult || 0.8,
    fWeaponDamageMult: params.fWeaponDamageMult || 1.0,
    fDeformationDamageMult: params.fDeformationDamageMult || 0.7,
    fEngineDamageMult: params.fEngineDamageMult || 1.2,
    fSpecialFlightModeRatio: params.fSpecialFlightModeRatio || 0.0,
  };

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ==================================================================== -->
<!-- Generated by ViceIntel Handling Studio (Zero-Syntax-Error XML Engine) -->
<!-- Target: resources/[vehicles]/custom_handling/handling.meta             -->
<!-- ==================================================================== -->
<CHandlingDataMgr>
  <HandlingData>
    <Item type="CHandlingData">
      <handlingName>${escapeLuaString(handlingName)}</handlingName>
      <fMass value="${p.fMass.toFixed(6)}" />
      <fInitialDragCoeff value="${p.fInitialDragCoeff.toFixed(6)}" />
      <fPercentSubmerged value="85.000000" />
      <vecCentreOfMassOffset x="0.000000" y="0.000000" z="0.000000" />
      <vecInertiaMultiplier x="1.000000" y="1.200000" z="1.500000" />
      <fDriveBiasFront value="${p.fDriveBiasFront.toFixed(6)}" />
      <nInitialDriveGears value="${Math.round(p.nInitialDriveGears)}" />
      <fInitialDriveForce value="${p.fInitialDriveForce.toFixed(6)}" />
      <fDriveInertia value="${p.fDriveInertia.toFixed(6)}" />
      <fClutchChangeRateScaleUpShift value="${p.fClutchChangeRateScaleUpShift.toFixed(6)}" />
      <fClutchChangeRateScaleDownShift value="${p.fClutchChangeRateScaleDownShift.toFixed(6)}" />
      <fInitialDriveMaxFlatVel value="${p.fInitialDriveMaxFlatVel.toFixed(6)}" />
      <fBrakeForce value="${p.fBrakeForce.toFixed(6)}" />
      <fBrakeBiasFront value="${p.fBrakeBiasFront.toFixed(6)}" />
      <fHandBrakeForce value="${p.fHandBrakeForce.toFixed(6)}" />
      <fSteeringLock value="${p.fSteeringLock.toFixed(6)}" />
      <fTractionCurveMax value="${p.fTractionCurveMax.toFixed(6)}" />
      <fTractionCurveMin value="${p.fTractionCurveMin.toFixed(6)}" />
      <fTractionCurveLateral value="${p.fTractionCurveLateral.toFixed(6)}" />
      <fTractionSpringDeltaMax value="${p.fTractionSpringDeltaMax.toFixed(6)}" />
      <fLowSpeedTractionLossMult value="${p.fLowSpeedTractionLossMult.toFixed(6)}" />
      <fCamberStiffnesss value="${p.fCamberStiffnesss.toFixed(6)}" />
      <fTractionBiasFront value="${p.fTractionBiasFront.toFixed(6)}" />
      <fTractionLossMult value="${p.fTractionLossMult.toFixed(6)}" />
      <fSuspensionForce value="${p.fSuspensionForce.toFixed(6)}" />
      <fSuspensionCompDamp value="${p.fSuspensionCompDamp.toFixed(6)}" />
      <fSuspensionReboundDamp value="${p.fSuspensionReboundDamp.toFixed(6)}" />
      <fSuspensionUpperLimit value="${p.fSuspensionUpperLimit.toFixed(6)}" />
      <fSuspensionLowerLimit value="${p.fSuspensionLowerLimit.toFixed(6)}" />
      <fSuspensionRaise value="${p.fSuspensionRaise.toFixed(6)}" />
      <fSuspensionBiasFront value="${p.fSuspensionBiasFront.toFixed(6)}" />
      <fAntiRollBarForce value="${p.fAntiRollBarForce.toFixed(6)}" />
      <fAntiRollBarBiasFront value="${p.fAntiRollBarBiasFront.toFixed(6)}" />
      <fRollCentreHeightFront value="${p.fRollCentreHeightFront.toFixed(6)}" />
      <fRollCentreHeightRear value="${p.fRollCentreHeightRear.toFixed(6)}" />
      <fCollisionDamageMult value="${p.fCollisionDamageMult.toFixed(6)}" />
      <fWeaponDamageMult value="${p.fWeaponDamageMult.toFixed(6)}" />
      <fDeformationDamageMult value="${p.fDeformationDamageMult.toFixed(6)}" />
      <fEngineDamageMult value="${p.fEngineDamageMult.toFixed(6)}" />
      <fSpecialFlightModeRatio value="${p.fSpecialFlightModeRatio.toFixed(6)}" />
      <fDownforceModifier value="${p.fDownforceModifier.toFixed(6)}" />
      <strModelFlags>440010</strModelFlags>
      <strHandlingFlags>0</strHandlingFlags>
      <strDamageFlags>0</strDamageFlags>
      <AIHandling>AVERAGE</AIHandling>
      <SubHandlingData>
        <Item type="NULL" />
        <Item type="NULL" />
        <Item type="NULL" />
      </SubHandlingData>
    </Item>
  </HandlingData>
</CHandlingDataMgr>`;
  return xml;
}

/**
 * Generates fxmanifest.lua for FiveM resource drag-and-drop bundle
 */
export function generateFxManifest(project: ServerConfigProject): string {
  const lines: string[] = [];
  lines.push(`fx_version 'cerulean'`);
  lines.push(`game 'gta5'`);
  lines.push(`lua54 'yes'`);
  lines.push(``);
  lines.push(`name '${escapeLuaString(project.projectName || 'vice_custom_pack')}'`);
  lines.push(`author 'ViceIntel B2B Studio'`);
  lines.push(`description 'Auto-generated high-fidelity FiveM resource bundle'`);
  lines.push(`version '1.0.0'`);
  lines.push(``);
  lines.push(`shared_scripts {`);
  lines.push(`    'config.lua',`);
  if (project.jobs && project.jobs.length > 0) {
    lines.push(`    'jobs.lua',`);
  }
  if (project.items && project.items.length > 0) {
    lines.push(`    'items.lua',`);
  }
  lines.push(`}`);
  lines.push(``);
  if (project.customHandling || project.category === 'handling_tuner' || project.category === 'full_bundle') {
    lines.push(`files {`);
    lines.push(`    'handling.meta',`);
    lines.push(`}`);
    lines.push(`data_file 'HANDLING_FILE' 'handling.meta'`);
  }
  return lines.join('\n');
}

/**
 * Generates master config.lua linking settings and economic multipliers
 */
export function generateConfigLua(project: ServerConfigProject): string {
  const lines: string[] = [];
  lines.push('-- ====================================================================');
  lines.push(`-- Resource: ${project.projectName || 'vice_server_config'}`);
  lines.push(`-- Framework: ${project.framework.toUpperCase()}`);
  lines.push('-- Generated: ' + new Date().toISOString());
  lines.push('-- ====================================================================');
  lines.push('');
  lines.push('Config = Config or {}');
  lines.push('');
  lines.push('-- [Server Identity & Framework Core]');
  lines.push(`Config.Framework = '${project.framework}'`);
  lines.push(`Config.Debug = false`);
  lines.push(`Config.CurrencySymbol = '$'`);
  lines.push('');
  lines.push('-- [Economy Baselines]');
  lines.push(`Config.PaycheckInterval = ${Math.max(5, project.economyBaselines?.paycheckIntervalMinutes || 15)} -- minutes between wage payouts`);
  lines.push(`Config.TaxRatePercentage = ${(project.economyBaselines?.taxRatePercentage || 8).toFixed(1)} -- government transaction tax`);
  lines.push(`Config.StartingCash = ${project.economyBaselines?.startingCashBalance || 5000}`);
  lines.push(`Config.StartingBank = ${project.economyBaselines?.startingBankBalance || 15000}`);
  lines.push(`Config.TargetSupercarPrice = ${project.economyBaselines?.targetSupercarPrice || 850000}`);
  lines.push('');
  lines.push('-- [Police & Illegal Multipliers]');
  lines.push('Config.MinCopsForIllegalActivities = 2');
  lines.push('Config.RiskPayoutScale = 1.35 -- multiplier for high-risk illicit deliveries');
  lines.push('');
  lines.push('-- [Anti-Exploit & Dirty Money Settings]');
  lines.push('Config.EnableLaunderingCut = true');
  lines.push('Config.LaunderingFeePercentage = 15.0');
  lines.push('Config.MaxCashCarryLimit = 500000 -- flags anti-cheat if exceeded');
  lines.push('');
  lines.push('return Config');
  return lines.join('\n');
}

/**
 * Computes deep mathematical economy health & progression metrics
 */
export function calculateEconomyMetrics(project: ServerConfigProject): EconomyMetrics {
  const jobs = project.jobs || [];
  const baselines = project.economyBaselines || {
    targetSupercarPrice: 850000,
    targetAverageHourlyWage: 3200,
    taxRatePercentage: 8,
    paycheckIntervalMinutes: 15,
    startingBankBalance: 15000,
    startingCashBalance: 5000
  };

  let totalHourlyWageSum = 0;
  let gradeCount = 0;
  let legalHourlyWageSum = 0;
  let legalGradeCount = 0;
  let illegalHourlyWageSum = 0;
  let illegalGradeCount = 0;

  const paychecksPerHour = 60 / Math.max(5, baselines.paycheckIntervalMinutes || 15);
  const taxFactor = 1 - Math.min(0.5, (baselines.taxRatePercentage || 8) / 100);

  const wageList: number[] = [];

  jobs.forEach((job) => {
    const isIllegal = Boolean(job.isIllegal || job.riskFactor > 1.4);
    const riskMultiplier = Math.max(1.0, job.riskFactor || 1.0);

    job.grades.forEach((g) => {
      // Net wage per hour = (Base Payment * Paychecks per hour * Risk Multiplier) * Tax factor
      const hourlyNet = g.payment * paychecksPerHour * riskMultiplier * taxFactor;
      totalHourlyWageSum += hourlyNet;
      gradeCount++;
      wageList.push(hourlyNet);

      if (isIllegal) {
        illegalHourlyWageSum += hourlyNet;
        illegalGradeCount++;
      } else {
        legalHourlyWageSum += hourlyNet;
        legalGradeCount++;
      }
    });
  });

  const avgHourlyWage = gradeCount > 0 ? Math.round(totalHourlyWageSum / gradeCount) : Math.round(baselines.targetAverageHourlyWage || 3200);
  const legalAvgHourlyWage = legalGradeCount > 0 ? Math.round(legalHourlyWageSum / legalGradeCount) : Math.round(avgHourlyWage * 0.85);
  const illegalAvgHourlyWage = illegalGradeCount > 0 ? Math.round(illegalHourlyWageSum / illegalGradeCount) : Math.round(avgHourlyWage * 1.5);

  const wageDisparityRatio = legalAvgHourlyWage > 0 ? Number((illegalAvgHourlyWage / legalAvgHourlyWage).toFixed(2)) : 1.0;

  const effectiveWage = Math.max(100, avgHourlyWage);
  const hoursToStarterCar = Number((25000 / effectiveWage).toFixed(1));
  const hoursToMidSedan = Number((85000 / effectiveWage).toFixed(1));
  const hoursToSupercar = Number((baselines.targetSupercarPrice / effectiveWage).toFixed(1));
  const hoursToLuxuryVilla = Number((3500000 / effectiveWage).toFixed(1));

  // Compute Gini Coefficient (Inequality)
  let giniIndex = 0.28;
  if (wageList.length > 1) {
    const sorted = [...wageList].sort((a, b) => a - b);
    const n = sorted.length;
    let sumOfDiffs = 0;
    let totalSum = 0;
    for (let i = 0; i < n; i++) {
      totalSum += sorted[i];
      for (let j = 0; j < n; j++) {
        sumOfDiffs += Math.abs(sorted[i] - sorted[j]);
      }
    }
    giniIndex = totalSum > 0 ? sumOfDiffs / (2 * n * totalSum) : 0.3;
  }

  // Velocity Score (Circulation health 0 - 100)
  // Optimal supercar grind is between 25 and 65 hours
  let velocityScore = 85;
  if (hoursToSupercar < 10) {
    velocityScore = Math.max(20, Math.round(100 - (10 - hoursToSupercar) * 8));
  } else if (hoursToSupercar > 100) {
    velocityScore = Math.max(20, Math.round(100 - (hoursToSupercar - 100) * 0.8));
  }

  // Rating determination
  let rating: EconomyMetrics['rating'] = 'Optimal';
  let ratingColor = 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30';
  const recommendations: string[] = [];

  if (wageDisparityRatio > 2.8) {
    rating = 'Extreme Disparity';
    ratingColor = 'text-rose-400 bg-rose-500/10 border-rose-500/30';
    recommendations.push('Illegal activities yield over 2.8x legal jobs. Legal civilian jobs risk complete abandonment within 2 weeks of server launch.');
  } else if (hoursToSupercar < 15) {
    rating = 'Hyper-Inflated';
    ratingColor = 'text-rose-400 bg-rose-500/10 border-rose-500/30';
    recommendations.push(`Players acquire top-tier supercars in under ${hoursToSupercar.toFixed(1)} hours. Increase vehicle prices or adjust paycheck intervals to prevent endgame economy collapse.`);
  } else if (hoursToSupercar > 80) {
    rating = 'Grindy';
    ratingColor = 'text-amber-400 bg-amber-500/10 border-amber-500/30';
    recommendations.push(`Grind to luxury tier exceeds ${hoursToSupercar.toFixed(1)} hours. Consider bumping entry salaries or lower sales taxes to reduce early player churn.`);
  } else if (hoursToSupercar < 25) {
    rating = 'Slightly Inflated';
    ratingColor = 'text-amber-400 bg-amber-500/10 border-amber-500/30';
    recommendations.push('Economy is slightly fast-paced. Suitable for casual roleplay, but consider adjusting high-tier salaries for long-term survival.');
  } else {
    rating = 'Optimal';
    ratingColor = 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30';
    recommendations.push('Economy velocity and wealth progression match competitive roleplay server standards. Balanced career advancement curves.');
  }

  return {
    avgHourlyWage: Math.round(avgHourlyWage),
    legalAvgHourlyWage: Math.round(legalAvgHourlyWage),
    illegalAvgHourlyWage: Math.round(illegalAvgHourlyWage),
    wageDisparityRatio: Number(wageDisparityRatio.toFixed(2)),
    hoursToStarterCar: Number(hoursToStarterCar.toFixed(1)),
    hoursToMidSedan: Number(hoursToMidSedan.toFixed(1)),
    hoursToSupercar: Number(hoursToSupercar.toFixed(1)),
    hoursToLuxuryVilla: Number(hoursToLuxuryVilla.toFixed(1)),
    giniIndex: Number(giniIndex.toFixed(2)),
    velocityScore,
    rating,
    ratingColor,
    recommendations
  };
}

/**
 * Curated Production-Ready Presets
 */
export const DEFAULT_PROJECT_PRESETS: ServerConfigProject[] = [
  {
    configId: 'preset-vice-qbcore-hardcore',
    ownerDiscordId: 'system_preset',
    projectName: 'Vice City 2026 Hardcore Realistic (QBCore)',
    framework: 'qbcore',
    category: 'full_bundle',
    economyBaselines: {
      targetSupercarPrice: 1250000,
      targetAverageHourlyWage: 2800,
      taxRatePercentage: 9.5,
      paycheckIntervalMinutes: 15,
      startingBankBalance: 12000,
      startingCashBalance: 2500
    },
    jobs: [
      {
        id: 'job-police',
        name: 'police',
        label: 'Vice City Police Department',
        defaultDuty: true,
        offDutyPay: false,
        riskFactor: 1.0,
        cycleMinutes: 15,
        isIllegal: false,
        grades: [
          { grade: 0, name: 'cadet', label: 'Cadet Officer', payment: 750 },
          { grade: 1, name: 'officer', label: 'Patrol Officer', payment: 1100 },
          { grade: 2, name: 'sergeant', label: 'Sergeant', payment: 1600 },
          { grade: 3, name: 'lieutenant', label: 'Lieutenant', payment: 2200 },
          { grade: 4, name: 'chief', label: 'Chief of Police', payment: 3200, isBoss: true }
        ]
      },
      {
        id: 'job-ems',
        name: 'ambulance',
        label: 'Vice City Fire & EMS',
        defaultDuty: true,
        offDutyPay: false,
        riskFactor: 1.0,
        cycleMinutes: 15,
        isIllegal: false,
        grades: [
          { grade: 0, name: 'paramedic_trainee', label: 'Paramedic Trainee', payment: 700 },
          { grade: 1, name: 'paramedic', label: 'Paramedic', payment: 1050 },
          { grade: 2, name: 'doctor', label: 'Attending Physician', payment: 1800 },
          { grade: 3, name: 'chief_doc', label: 'Medical Director', payment: 2800, isBoss: true }
        ]
      },
      {
        id: 'job-mechanic',
        name: 'mechanic',
        label: 'Ocean Drive Customs',
        defaultDuty: false,
        offDutyPay: false,
        riskFactor: 1.0,
        cycleMinutes: 10,
        isIllegal: false,
        grades: [
          { grade: 0, name: 'apprentice', label: 'Apprentice', payment: 600 },
          { grade: 1, name: 'mechanic', label: 'Lead Tech', payment: 1200 },
          { grade: 2, name: 'owner', label: 'Shop Boss', payment: 2400, isBoss: true }
        ]
      },
      {
        id: 'job-smuggler',
        name: 'contraband_runner',
        label: 'Everglades Smuggler',
        defaultDuty: false,
        offDutyPay: false,
        riskFactor: 2.3,
        cycleMinutes: 20,
        isIllegal: true,
        grades: [
          { grade: 0, name: 'lookout', label: 'Lookout', payment: 1400 },
          { grade: 1, name: 'boat_courier', label: 'Airboat Courier', payment: 2600 },
          { grade: 2, name: 'ringleader', label: 'Cartel Lieutenant', payment: 4500, isBoss: true }
        ]
      }
    ],
    items: [
      {
        name: 'lockpick',
        label: 'Advanced Lockpick',
        weight: 350,
        type: 'item',
        image: 'lockpick.png',
        unique: false,
        useable: true,
        shouldClose: true,
        description: 'Tungsten-carbide tension wrench and picks for high-security electronic and pin tumblers.',
        buyPrice: 850,
        sellPrice: 400
      },
      {
        name: 'oxy_bottle',
        label: 'Oxycodone Prescription',
        weight: 150,
        type: 'consumable',
        image: 'oxy.png',
        unique: false,
        useable: true,
        shouldClose: true,
        description: 'Pharmaceutical painkiller. Restores health rapidly and eases weapon recoil.',
        buyPrice: 150,
        sellPrice: 450,
        decayRate: 5
      },
      {
        name: 'repairkit',
        label: 'Professional Toolkit',
        weight: 2500,
        type: 'item',
        image: 'repairkit.png',
        unique: false,
        useable: true,
        shouldClose: true,
        description: 'Includes torque wrenches, spare belts, and tire plugs for roadside emergency repair.',
        buyPrice: 1200,
        sellPrice: 600
      },
      {
        name: 'crypto_stick',
        label: 'Encrypted Ledger Stick',
        weight: 100,
        type: 'item',
        image: 'cryptostick.png',
        unique: true,
        useable: true,
        shouldClose: true,
        description: 'Hardware wallet containing untraceable ViceCoin transactions from darknet heists.',
        buyPrice: 0,
        sellPrice: 8500
      }
    ],
    customHandling: {
      fMass: 1620,
      fInitialDragCoeff: 7.8,
      fInitialDriveForce: 0.42,
      fDriveBiasFront: 0.35,
      fBrakeForce: 1.25,
      fSteeringLock: 39.0,
      fTractionCurveMax: 2.55,
      fDownforceModifier: 2.1
    },
    generatedCode: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isProExport: true
  },
  {
    configId: 'preset-southbeach-esx',
    ownerDiscordId: 'system_preset',
    projectName: 'South Beach Fast-Paced Fun (ESX Legacy)',
    framework: 'esx_legacy',
    category: 'full_bundle',
    economyBaselines: {
      targetSupercarPrice: 650000,
      targetAverageHourlyWage: 5200,
      taxRatePercentage: 5.0,
      paycheckIntervalMinutes: 10,
      startingBankBalance: 30000,
      startingCashBalance: 10000
    },
    jobs: [
      {
        id: 'job-police-esx',
        name: 'police',
        label: 'Metro Police',
        defaultDuty: true,
        offDutyPay: false,
        riskFactor: 1.0,
        cycleMinutes: 10,
        isIllegal: false,
        grades: [
          { grade: 0, name: 'recruit', label: 'Recruit', payment: 1200 },
          { grade: 1, name: 'officer', label: 'Officer', payment: 2000 },
          { grade: 2, name: 'boss', label: 'Chief of Police', payment: 4500, isBoss: true }
        ]
      },
      {
        id: 'job-taxi-esx',
        name: 'taxi',
        label: 'Downtown Cab Co.',
        defaultDuty: false,
        offDutyPay: false,
        riskFactor: 1.0,
        cycleMinutes: 8,
        isIllegal: false,
        grades: [
          { grade: 0, name: 'driver', label: 'Chauffeur', payment: 1400 },
          { grade: 1, name: 'owner', label: 'Fleet Manager', payment: 3000, isBoss: true }
        ]
      },
      {
        id: 'job-cartel-esx',
        name: 'cartel',
        label: 'Vice Syndicate',
        defaultDuty: false,
        offDutyPay: false,
        riskFactor: 2.0,
        cycleMinutes: 12,
        isIllegal: true,
        grades: [
          { grade: 0, name: 'enforcer', label: 'Street Enforcer', payment: 2500 },
          { grade: 1, name: 'underboss', label: 'Underboss', payment: 5500, isBoss: true }
        ]
      }
    ],
    items: [
      {
        name: 'medikit',
        label: 'First Aid Kit',
        weight: 500,
        type: 'consumable',
        image: 'medikit.png',
        unique: false,
        useable: true,
        shouldClose: true,
        description: 'Complete trauma kit with epinephrine and bandages.',
        buyPrice: 500,
        sellPrice: 200
      },
      {
        name: 'blowtorch',
        label: 'Thermal Cutting Torch',
        weight: 3200,
        type: 'item',
        image: 'blowtorch.png',
        unique: false,
        useable: true,
        shouldClose: true,
        description: 'Industrial oxygen-acetylene torch capable of slicing armored bank vault hinges.',
        buyPrice: 3500,
        sellPrice: 1800
      }
    ],
    customHandling: {
      fMass: 1450,
      fInitialDragCoeff: 6.5,
      fInitialDriveForce: 0.48,
      fDriveBiasFront: 0.0,
      fBrakeForce: 1.35,
      fSteeringLock: 42.0,
      fTractionCurveMax: 2.65,
      fDownforceModifier: 2.4
    },
    generatedCode: '',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isProExport: true
  }
];
