'use client';

import React, { useState } from 'react';
import JSZip from 'jszip';
import {
  ServerConfigProject,
  generateQBCoreJobs,
  generateESXJobs,
  generateQBCoreItems,
  generateESXItems,
  generateHandlingXML,
  generateConfigLua,
  generateFxManifest
} from '../../lib/lua-generators';
import {
  Code,
  Copy,
  Check,
  Download,
  FileArchive,
  Crown,
  FileCode,
  Sparkles,
  Lock,
  Layers,
  Database,
  ExternalLink
} from 'lucide-react';

interface LuaCodePreviewProps {
  project: ServerConfigProject;
  isProUser: boolean;
  onOpenProModal: () => void;
}

type CodeTab = 'config' | 'jobs' | 'items' | 'handling' | 'fxmanifest' | 'sql';

export const LuaCodePreview: React.FC<LuaCodePreviewProps> = ({
  project,
  isProUser,
  onOpenProModal
}) => {
  const [activeTab, setActiveTab] = useState<CodeTab>('jobs');
  const [hasCopied, setHasCopied] = useState<boolean>(false);
  const [isZipping, setIsZipping] = useState<boolean>(false);

  // Generate deterministic codes
  const configLua = generateConfigLua(project);
  const jobsLua = project.framework === 'esx_legacy' ? generateESXJobs(project.jobs) : generateQBCoreJobs(project.jobs);
  const itemsLua = project.framework === 'esx_legacy' ? generateESXItems(project.items) : generateQBCoreItems(project.items);
  const handlingXml = generateHandlingXML(project.customHandling || {});
  const fxmanifestLua = generateFxManifest(project);

  // Extract SQL migrations if ESX
  const sqlContent = `-- Database Migrations for ${project.projectName}
-- Framework: ${project.framework.toUpperCase()}
-- Generated at: ${new Date().toISOString()}

${project.jobs.map(j => {
  const jk = j.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
  return `INSERT IGNORE INTO \`jobs\` (\`name\`, \`label\`, \`whitelisted\`) VALUES ('${jk}', '${j.label}', ${j.riskFactor >= 1.5 ? 1 : 0});\n` +
    j.grades.map(g => `INSERT IGNORE INTO \`job_grades\` (\`job_name\`, \`grade\`, \`name\`, \`label\`, \`salary\`, \`skin_male\`, \`skin_female\`) VALUES ('${jk}', ${g.grade}, '${g.name}', '${g.label || g.name}', ${Math.round(g.payment)}, '{}', '{}');`).join('\n');
}).join('\n\n')}

${project.items.map(it => {
  const ik = it.name.toLowerCase().trim().replace(/[^a-z0-9_]/g, '_');
  return `INSERT IGNORE INTO \`items\` (\`name\`, \`label\`, \`weight\`, \`rare\`, \`can_remove\`) VALUES ('${ik}', '${it.label}', ${Math.max(1, Math.round(it.weight / 100))}, 0, 1);`;
}).join('\n')}`;

  const getCurrentCode = (): { filename: string; code: string; language: string } => {
    switch (activeTab) {
      case 'config':
        return { filename: 'config.lua', code: configLua, language: 'lua' };
      case 'jobs':
        return { filename: 'jobs.lua', code: jobsLua, language: 'lua' };
      case 'items':
        return { filename: 'items.lua', code: itemsLua, language: 'lua' };
      case 'handling':
        return { filename: 'handling.meta', code: handlingXml, language: 'xml' };
      case 'fxmanifest':
        return { filename: 'fxmanifest.lua', code: fxmanifestLua, language: 'lua' };
      case 'sql':
        return { filename: 'schema.sql', code: sqlContent, language: 'sql' };
    }
  };

  const activeCodeData = getCurrentCode();

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(activeCodeData.code);
      setHasCopied(true);
      setTimeout(() => setHasCopied(false), 2000);
    } catch (err) {
      console.warn('Clipboard write failed:', err);
    }
  };

  // Single file download
  const handleDownloadSingle = () => {
    const blob = new Blob([activeCodeData.code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = activeCodeData.filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Multi-file ZIP Bundle Export with JSZip
  const handleExportZip = async () => {
    if (!isProUser) {
      onOpenProModal();
      return;
    }

    try {
      setIsZipping(true);
      const zip = new JSZip();
      const folderName = project.projectName
        ? project.projectName.toLowerCase().replace(/[^a-z0-9_-]/g, '_')
        : 'vice_server_resource';

      const resFolder = zip.folder(folderName);
      if (!resFolder) throw new Error('Could not create folder');

      resFolder.file('fxmanifest.lua', fxmanifestLua);
      resFolder.file('config.lua', configLua);
      resFolder.file('jobs.lua', jobsLua);
      resFolder.file('items.lua', itemsLua);
      resFolder.file('handling.meta', handlingXml);
      resFolder.file('schema.sql', sqlContent);
      resFolder.file(
        'README.md',
        `# ${project.projectName || 'FiveM Server Resource Bundle'}
Generated by ViceIntel No-Code Lua & XML Studio (Zero-Syntax-Error Engine)

## Installation Guide
1. Drag the folder \`${folderName}\` into your FiveM server's \`resources/[vice]/\` directory.
2. If using MySQL/MariaDB for ESX, execute \`schema.sql\` in HeidiSQL / phpMyAdmin.
3. Add the startup command to your \`server.cfg\`:
\`\`\`cfg
ensure ${folderName}
\`\`\`
4. Restart your FiveM server or run \`refresh\` and \`ensure ${folderName}\` in server console.

Framework: ${project.framework.toUpperCase()}
Generated: ${new Date().toUTCString()}
`
      );

      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${folderName}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (zipErr) {
      console.error('ZIP generation error:', zipErr);
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="flex flex-col h-full bg-[#090d13] border border-white/10 rounded-xl overflow-hidden shadow-2xl">
      {/* Code Viewer Tab Header */}
      <div className="p-3 border-b border-white/10 bg-black/60 flex flex-wrap items-center justify-between gap-2">
        {/* File Tabs */}
        <div className="flex items-center gap-1 overflow-x-auto scrollbar-none">
          <button
            onClick={() => setActiveTab('jobs')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'jobs'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            jobs.lua
          </button>

          <button
            onClick={() => setActiveTab('items')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'items'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            items.lua
          </button>

          <button
            onClick={() => setActiveTab('config')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'config'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            config.lua
          </button>

          <button
            onClick={() => setActiveTab('handling')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'handling'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            handling.meta
          </button>

          <button
            onClick={() => setActiveTab('fxmanifest')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'fxmanifest'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <FileArchive className="w-3.5 h-3.5" />
            fxmanifest.lua
          </button>

          <button
            onClick={() => setActiveTab('sql')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'sql'
                ? 'bg-rose-600 text-white shadow-lg shadow-rose-600/30'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            <Database className="w-3.5 h-3.5" />
            schema.sql
          </button>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-bold rounded-lg border border-white/10 transition-colors"
            title="Copy current file code"
          >
            {hasCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{hasCopied ? 'Copied!' : 'Copy Lua'}</span>
          </button>

          <button
            onClick={handleDownloadSingle}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-bold rounded-lg border border-white/10 transition-colors"
            title="Download active file"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </button>

          <button
            onClick={handleExportZip}
            disabled={isZipping}
            className={`flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold rounded-lg transition-all shadow-lg ${
              isProUser
                ? 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white shadow-emerald-600/30'
                : 'bg-gradient-to-r from-amber-600 to-rose-600 hover:from-amber-500 hover:to-rose-500 text-white shadow-rose-600/30'
            }`}
          >
            {isProUser ? (
              <>
                <FileArchive className="w-3.5 h-3.5" />
                <span>{isZipping ? 'Bundling...' : 'Export ZIP Bundle'}</span>
              </>
            ) : (
              <>
                <Crown className="w-3.5 h-3.5 text-amber-300" />
                <span>Export Pro ZIP</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Monospaced Code Stream with Syntax-Highlight Visual */}
      <div className="flex-1 overflow-auto bg-[#06090e] p-4 font-mono text-[11px] leading-relaxed text-emerald-300 select-text">
        <pre className="whitespace-pre overflow-x-auto text-zinc-200">
          <code>
            {activeCodeData.code.split('\n').map((line, lineIndex) => {
              const isComment = line.trim().startsWith('--') || line.trim().startsWith('/*') || line.trim().startsWith('<!--');
              const isKey = line.includes('QBShared.') || line.includes('Config.') || line.includes('<Item') || line.includes('fx_version');
              const isNumber = line.includes('=') && !isNaN(Number(line.split('=')[1]?.trim()?.replace(',', '')));

              return (
                <div key={lineIndex} className="table-row hover:bg-white/5">
                  <span className="table-cell pr-4 select-none text-zinc-600 text-right w-8">
                    {lineIndex + 1}
                  </span>
                  <span
                    className={`table-cell pl-2 ${
                      isComment
                        ? 'text-zinc-500 italic'
                        : isKey
                        ? 'text-rose-400 font-bold'
                        : isNumber
                        ? 'text-cyan-300'
                        : 'text-zinc-300'
                    }`}
                  >
                    {line}
                  </span>
                </div>
              );
            })}
          </code>
        </pre>
      </div>

      {/* Bottom Status Bar */}
      <div className="px-4 py-2 bg-black/80 border-t border-white/10 flex flex-wrap items-center justify-between text-[11px] text-zinc-400">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1 text-emerald-400 font-bold">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Zero Syntax Errors (AST Safe)
          </span>
          <span className="hidden sm:inline text-zinc-600">|</span>
          <span className="hidden sm:inline">Lines: {activeCodeData.code.split('\n').length}</span>
          <span className="hidden sm:inline text-zinc-600">|</span>
          <span className="hidden sm:inline">Size: {new Blob([activeCodeData.code]).size} bytes</span>
        </div>

        <div className="flex items-center gap-2">
          {isProUser ? (
            <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 font-bold flex items-center gap-1 border border-emerald-500/30">
              <Crown className="w-3 h-3 text-emerald-400" />
              Pro License Active
            </span>
          ) : (
            <button
              onClick={onOpenProModal}
              className="text-amber-400 hover:text-amber-300 font-bold flex items-center gap-1 transition-colors"
            >
              <Crown className="w-3 h-3" />
              Unlock Multi-Resource ZIP & AI Studio ($29/mo)
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
